### ISSUE TITLE
modelPath not pointing to the right location

### ISSUE THREAD

**Issue by jcarpent** [Gepetto/example-robot-data#35] opened 2020-06-19 14:33 UTC
@nim65s @cmastalli 

I think there is a current issue in the way the Python libs is retrieving the absolute mesh PATH.
Currently, all the meshes are related to `package:\\example-robot-data/robots/foo_description` but when looking for the mesh path, this one is pointing to:
`${CMAKE_INSTALL_PREFIX}/example-robot-data/robots`, meaning that there is an `example-robot-data/robots` which is duplicated.

PS: you can use ` example_robot_data.getModelPath('')` to retrieve the full mesh path as currently returned.

**Comment by nim65s** [comment] 2020-06-19 14:37
ref mainly #19, but also #9 & #21

**Comment by nim65s** [comment] 2020-06-19 14:54
On my side, 
```python
>>> example_robot_data.getModelPath('/panda_description/urdf/panda.urdf')
'/home/gsaurel/local/robotpkg/install/share/example-robot-data/robots'
````

So I think this is the intended behavior.

**Comment by jcarpent** [comment] 2020-06-19 15:33
But it the path for the visuals should be: `/home/gsaurel/local/robotpkg/install/share`

**Comment by nim65s** [comment] 2020-06-19 16:33
fixed in 6a1807747f58ba467c67e017f4056451ec12efb8 ; @wxmerkt @cmastalli : can you test that please ?

**Comment by nim65s** [comment] 2020-06-19 16:34
I guess the list implies that we could provide the old one and the new, just to be sure… But this is cluttered enough already, so if we can avoid that it's better.

**Comment by jcarpent** [comment] 2020-06-19 17:04
Thanks a lot @nim65s for your precious help.

**Comment by wxmerkt** [comment] 2020-06-19 18:13
From reading the commit, it looks good (didn't run it locally)

**Closed** 2020-06-20 08:14 UTC
Labels: bug
